name: Enforce Branch Naming

on:
  pull_request:
    branches:
      - review/dba

jobs:
  enforce-branch-naming:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Branch Name
        run: |
          sourceBranchName = "${{github.head_ref}}"
          echo "sourceBranchName -> $sourceBranchName"
          if ! [[ "$sourceBranchName" =~ ^[0-9]+(\.[0-9]+)*$ ]]; then
            echo "Error: The source branch name must only contain numerics/digits and decimals/dots"
            exit 1
          fi
