name: Enforce Branch Naming

on:
  pull_request:
    branches:
      - review/dba

jobs:
  enforce-branch-naming:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Branch Name
        run: |
          branch_name=$(echo "${GITHUB_REF#refs/heads/}")
          if ! [[ "$branch_name" =~ ^[0-9]+(\.[0-9]+)*$ ]]; then
            echo "Error: Branch name must only contain digits and decimals."
            exit 1
          fi
